'test'

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,21 +4,20 @@
 #!/bin/sh
 # Redirect output to stderr.
 exec 1>&2
-# enable user input
-exec < /dev/tty
 
+# Define the regular expression for console.log
 consoleregexp='console.log'
-# CHECK
+
+# Check if any staged files contain console.log
 if test $(git diff --cached | grep $consoleregexp | wc -l) != 0
 then 
-  exec git diff --cached | grep -ne $consoleregexp
-  read -p "There are some occurrences of console.log at your modification. Are you sure want to continue? (y/n)" yn
-  echo $yn | grep ^[Yy]$
-  if [ $? -eq 0 ] 
-  then
-    exit 0; #THE USER WANTS TO CONTINUE
-  else
-    exit 1; # THE USER DONT WANT TO CONTINUE SO ROLLBACK
-  fi
+  # Show the occurrences of console.log with file names and line numbers
+  echo "ERROR: Found console.log in the following files:"
+  git diff --cached | grep -ne $consoleregexp
+  
+  # Exit with status 1 to prevent the commit
+  exit 1
 fi
+
+# Run lint-staged if no console.log is found
 npx lint-staged
